// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/calculate-mortgage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculate-mortgage.post').default>>>>
    }
    '/api/property/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/property/[id].get').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/tenant-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant-config.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}